const itemDict = {
    "Coco Beans": "INK_SACK:3",
    "Lapis Lazuli": "INK_SACK:4",
    "Corrupted Bait": "CORRUPTED_BAIT",
    "Tarantula Web": "TARANTULA_WEB",
    "Enchantment Ultimate No Pain No Gain 2":
        "ENCHANTMENT_ULTIMATE_NO_PAIN_NO_GAIN_2",
    "Enchantment Ultimate No Pain No Gain 1":
        "ENCHANTMENT_ULTIMATE_NO_PAIN_NO_GAIN_1",
    "Dungeon Trap": "DUNGEON_TRAP",
    "Dark Orb": "DARK_ORB",
    "Enchantment Protection 7": "ENCHANTMENT_PROTECTION_7",
    "Enchantment Protection 6": "ENCHANTMENT_PROTECTION_6",
    "Essence Dragon": "ESSENCE_DRAGON",
    "Ritual Residue": "RITUAL_RESIDUE",
    "Enchantment Protection 1": "ENCHANTMENT_PROTECTION_1",
    "Giant Fragment Laser": "GIANT_FRAGMENT_LASER",
    "Enchantment Protection 5": "ENCHANTMENT_PROTECTION_5",
    "Enchanted Melon": "ENCHANTED_MELON",
    "Enchantment Protection 4": "ENCHANTMENT_PROTECTION_4",
    "Enchantment Protection 3": "ENCHANTMENT_PROTECTION_3",
    "Enchantment Protection 2": "ENCHANTMENT_PROTECTION_2",
    "Enchantment Turbo Coco 1": "ENCHANTMENT_TURBO_COCO_1",
    "Enchantment Turbo Coco 5": "ENCHANTMENT_TURBO_COCO_5",
    "Enchantment Turbo Coco 4": "ENCHANTMENT_TURBO_COCO_4",
    "Enchantment Turbo Coco 3": "ENCHANTMENT_TURBO_COCO_3",
    "Enchanted Blaze Rod": "ENCHANTED_BLAZE_ROD",
    "Enchantment Turbo Coco 2": "ENCHANTMENT_TURBO_COCO_2",
    "Enchanted Brown Mushroom": "ENCHANTED_BROWN_MUSHROOM",
    "Goblin Egg Yellow": "GOBLIN_EGG_YELLOW",
    "Enchanted Glistering Melon": "ENCHANTED_GLISTERING_MELON",
    "Enchantment Corruption 5": "ENCHANTMENT_CORRUPTION_5",
    "Enchantment Corruption 4": "ENCHANTMENT_CORRUPTION_4",
    "Enchantment Corruption 3": "ENCHANTMENT_CORRUPTION_3",
    "Protector Fragment": "PROTECTOR_FRAGMENT",
    "Enchantment Corruption 2": "ENCHANTMENT_CORRUPTION_2",
    "Enchantment Corruption 1": "ENCHANTMENT_CORRUPTION_1",
    "Enchanted Melon Block": "ENCHANTED_MELON_BLOCK",
    "Rock Gemstone": "ROCK_GEMSTONE",
    "Condensed Fermento": "CONDENSED_FERMENTO",
    Diamond: "DIAMOND",
    Cobblestone: "COBBLESTONE",
    "Enchanted Pufferfish": "ENCHANTED_PUFFERFISH",
    "Perfect Ruby Gem": "PERFECT_RUBY_GEM",
    "Minion Expander": "MINION_EXPANDER",
    "End Stone Shulker": "END_STONE_SHULKER",
    "Enchantment Cayenne 5": "ENCHANTMENT_CAYENNE_5",
    "Enchanted Hard Stone": "ENCHANTED_HARD_STONE",
    "Enchantment Cayenne 4": "ENCHANTMENT_CAYENNE_4",
    "Ender Monocle": "ENDER_MONOCLE",
    "Kelvin Inverter": "KELVIN_INVERTER",
    "Refined Diamond": "REFINED_DIAMOND",
    "Hazmat Enderman": "HAZMAT_ENDERMAN",
    "Luxurious Spool": "LUXURIOUS_SPOOL",
    "Flawed Opal Gem": "FLAWED_OPAL_GEM",
    "Enchantment Cayenne 3": "ENCHANTMENT_CAYENNE_3",
    Pork: "PORK",
    "Enchantment Cayenne 2": "ENCHANTMENT_CAYENNE_2",
    "Enchantment Cayenne 1": "ENCHANTMENT_CAYENNE_1",
    "Enchantment Ender Slayer 1": "ENCHANTMENT_ENDER_SLAYER_1",
    "Ultimate Carrot Candy": "ULTIMATE_CARROT_CANDY",
    "Solar Panel": "SOLAR_PANEL",
    "Enchantment Fire Aspect 1": "ENCHANTMENT_FIRE_ASPECT_1",
    "Dark Oak Wood": "LOG_2:1",
    "Undead Catalyst": "UNDEAD_CATALYST",
    "Enchantment Turbo Cactus 5": "ENCHANTMENT_TURBO_CACTUS_5",
    "Enchanted Snow Block": "ENCHANTED_SNOW_BLOCK",
    "Enchantment Turbo Cactus 4": "ENCHANTMENT_TURBO_CACTUS_4",
    "Enchantment Turbo Cactus 3": "ENCHANTMENT_TURBO_CACTUS_3",
    "Enchantment Turbo Cactus 2": "ENCHANTMENT_TURBO_CACTUS_2",
    "Enchantment Fire Aspect 2": "ENCHANTMENT_FIRE_ASPECT_2",
    "Enchantment Fire Aspect 3": "ENCHANTMENT_FIRE_ASPECT_3",
    "Enchantment Turbo Cactus 1": "ENCHANTMENT_TURBO_CACTUS_1",
    "Enchantment Ender Slayer 5": "ENCHANTMENT_ENDER_SLAYER_5",
    "Enchantment Ender Slayer 4": "ENCHANTMENT_ENDER_SLAYER_4",
    "Enchantment Ender Slayer 3": "ENCHANTMENT_ENDER_SLAYER_3",
    "Enchantment Ender Slayer 2": "ENCHANTMENT_ENDER_SLAYER_2",
    "Enchantment Ender Slayer 7": "ENCHANTMENT_ENDER_SLAYER_7",
    "Enchantment Ender Slayer 6": "ENCHANTMENT_ENDER_SLAYER_6",
    "Enchantment Sharpness 1": "ENCHANTMENT_SHARPNESS_1",
    "Dungeon Decoy": "DUNGEON_DECOY",
    "Enchantment Sharpness 5": "ENCHANTMENT_SHARPNESS_5",
    "Jerry Box Golden": "JERRY_BOX_GOLDEN",
    "Enchantment Sharpness 4": "ENCHANTMENT_SHARPNESS_4",
    "Enchantment Sharpness 3": "ENCHANTMENT_SHARPNESS_3",
    "Enchantment Sharpness 2": "ENCHANTMENT_SHARPNESS_2",
    "Enchantment Big Brain 4": "ENCHANTMENT_BIG_BRAIN_4",
    "Enchantment Big Brain 5": "ENCHANTMENT_BIG_BRAIN_5",
    "Enchantment Big Brain 3": "ENCHANTMENT_BIG_BRAIN_3",
    "Enchanted Carrot On A Stick": "ENCHANTED_CARROT_ON_A_STICK",
    "Enchantment Thunderlord 7": "ENCHANTMENT_THUNDERLORD_7",
    "Enchantment Thunderlord 6": "ENCHANTMENT_THUNDERLORD_6",
    "Enchantment Turbo Melon 5": "ENCHANTMENT_TURBO_MELON_5",
    "Derelict Ashe": "DERELICT_ASHE",
    "Fly Swatter": "FLY_SWATTER",
    "Enchantment Thunderlord 3": "ENCHANTMENT_THUNDERLORD_3",
    "Enchantment Thunderlord 2": "ENCHANTMENT_THUNDERLORD_2",
    "Enchantment Sharpness 7": "ENCHANTMENT_SHARPNESS_7",
    "Enchantment Thunderlord 5": "ENCHANTMENT_THUNDERLORD_5",
    "Enchantment Sharpness 6": "ENCHANTMENT_SHARPNESS_6",
    "Enchantment Thunderlord 4": "ENCHANTMENT_THUNDERLORD_4",
    "Enchanted Acacia Log": "ENCHANTED_ACACIA_LOG",
    "Enchantment Mana Steal 1": "ENCHANTMENT_MANA_STEAL_1",
    "Enchantment Mana Steal 2": "ENCHANTMENT_MANA_STEAL_2",
    "Enchantment Thunderlord 1": "ENCHANTMENT_THUNDERLORD_1",
    "Enchantment Mana Steal 3": "ENCHANTMENT_MANA_STEAL_3",
    Sand: "SAND",
    "Ancient Claw": "ANCIENT_CLAW",
    "Plasma Bucket": "PLASMA_BUCKET",
    "Enchantment Turbo Melon 3": "ENCHANTMENT_TURBO_MELON_3",
    "Enchantment Strong Mana 7": "ENCHANTMENT_STRONG_MANA_7",
    "Enchanted Ghast Tear": "ENCHANTED_GHAST_TEAR",
    "Enchantment Turbo Melon 4": "ENCHANTMENT_TURBO_MELON_4",
    "Enchantment Strong Mana 6": "ENCHANTMENT_STRONG_MANA_6",
    "Enchantment Turbo Melon 1": "ENCHANTMENT_TURBO_MELON_1",
    "Enchanted Cocoa": "ENCHANTED_COCOA",
    "Enchantment Strong Mana 5": "ENCHANTMENT_STRONG_MANA_5",
    "Enchantment Turbo Melon 2": "ENCHANTMENT_TURBO_MELON_2",
    "Enchantment Strong Mana 4": "ENCHANTMENT_STRONG_MANA_4",
    "Enchantment Strong Mana 3": "ENCHANTMENT_STRONG_MANA_3",
    "Amber Material": "AMBER_MATERIAL",
    "Enchantment Strong Mana 2": "ENCHANTMENT_STRONG_MANA_2",
    "Enchantment Strong Mana 1": "ENCHANTMENT_STRONG_MANA_1",
    "Fine Topaz Gem": "FINE_TOPAZ_GEM",
    "Carrot Bait": "CARROT_BAIT",
    "Fine Ruby Gem": "FINE_RUBY_GEM",
    "Hypergolic Ionized Ceramics": "HYPERGOLIC_IONIZED_CERAMICS",
    "Hay Block": "HAY_BLOCK",
    "Enchanted Rotten Flesh": "ENCHANTED_ROTTEN_FLESH",
    "Enchanted Grilled Pork": "ENCHANTED_GRILLED_PORK",
    "Enchanted Ancient Claw": "ENCHANTED_ANCIENT_CLAW",
    "Enchantment Hardened Mana 1": "ENCHANTMENT_HARDENED_MANA_1",
    "Overgrown Grass": "OVERGROWN_GRASS",
    "Full Chum Bucket": "FULL_CHUM_BUCKET",
    "Pumpkin Bomb": "PUMPKIN_BOMB",
    "Enchantment Hardened Mana 3": "ENCHANTMENT_HARDENED_MANA_3",
    "Enchantment Hardened Mana 2": "ENCHANTMENT_HARDENED_MANA_2",
    "Enchantment Ultimate Combo 1": "ENCHANTMENT_ULTIMATE_COMBO_1",
    "Soulflow Engine": "SOULFLOW_ENGINE",
    "Enchantment Ultimate Combo 2": "ENCHANTMENT_ULTIMATE_COMBO_2",
    "Enchantment Ultimate Combo 5": "ENCHANTMENT_ULTIMATE_COMBO_5",
    "Pet Item Toy Jerry": "PET_ITEM_TOY_JERRY",
    "Enchantment Ultimate Combo 3": "ENCHANTMENT_ULTIMATE_COMBO_3",
    "Enchanted Lava Bucket": "ENCHANTED_LAVA_BUCKET",
    "Enchantment Ultimate Combo 4": "ENCHANTMENT_ULTIMATE_COMBO_4",
    Pufferfish: "RAW_FISH:3",
    "Bubba Blister": "BUBBA_BLISTER",
    "Enchantment Strong Mana 9": "ENCHANTMENT_STRONG_MANA_9",
    "Enchantment Strong Mana 8": "ENCHANTMENT_STRONG_MANA_8",
    "Diamond Atom": "DIAMOND_ATOM",
    Clownfish: "RAW_FISH:2",
    "Precursor Gear": "PRECURSOR_GEAR",
    "Raw Salmon": "RAW_FISH:1",
    "Goblin Egg Red": "GOBLIN_EGG_RED",
    "Enchantment Turbo Warts 1": "ENCHANTMENT_TURBO_WARTS_1",
    "Enchantment Turbo Warts 2": "ENCHANTMENT_TURBO_WARTS_2",
    "Enchantment Turbo Warts 3": "ENCHANTMENT_TURBO_WARTS_3",
    "Enchantment Turbo Warts 4": "ENCHANTMENT_TURBO_WARTS_4",
    "Enchantment Turbo Warts 5": "ENCHANTMENT_TURBO_WARTS_5",
    "Whale Bait": "WHALE_BAIT",
    Sponge: "SPONGE",
    "Enchanted Dark Oak Log": "ENCHANTED_DARK_OAK_LOG",
    "Flawless Topaz Gem": "FLAWLESS_TOPAZ_GEM",
    "Enchantment Hardened Mana 5": "ENCHANTMENT_HARDENED_MANA_5",
    "Enchantment Hardened Mana 4": "ENCHANTMENT_HARDENED_MANA_4",
    "Enchantment Hardened Mana 7": "ENCHANTMENT_HARDENED_MANA_7",
    "Enchantment Hardened Mana 6": "ENCHANTMENT_HARDENED_MANA_6",
    "Enchantment Ultimate No Pain No Gain 4":
        "ENCHANTMENT_ULTIMATE_NO_PAIN_NO_GAIN_4",
    "Enchantment Hardened Mana 9": "ENCHANTMENT_HARDENED_MANA_9",
    "Enchantment Hardened Mana 8": "ENCHANTMENT_HARDENED_MANA_8",
    "Enchantment Ultimate No Pain No Gain 3":
        "ENCHANTMENT_ULTIMATE_NO_PAIN_NO_GAIN_3",
    "Enchantment Ultimate No Pain No Gain 5":
        "ENCHANTMENT_ULTIMATE_NO_PAIN_NO_GAIN_5",
    "Enchanted Raw Chicken": "ENCHANTED_RAW_CHICKEN",
    "Enchanted Water Lily": "ENCHANTED_WATER_LILY",
    "Red Scarf": "RED_SCARF",
    "Spruce Wood": "LOG:1",
    "Titanium Ore": "TITANIUM_ORE",
    "Robotron Reflector": "ROBOTRON_REFLECTOR",
    "Blue Shark Tooth": "BLUE_SHARK_TOOTH",
    "Jungle Wood": "LOG:3",
    "Chili Pepper": "CHILI_PEPPER",
    "Birch Wood": "LOG:2",
    "Sil Ex": "SIL_EX",
    "Enchanted Cactus": "ENCHANTED_CACTUS",
    "Salt Cube": "SALT_CUBE",
    Onyx: "ONYX",
    "Enchanted Cooked Salmon": "ENCHANTED_COOKED_SALMON",
    "Enchanted Sulphur": "ENCHANTED_SULPHUR",
    "Enchanted Seeds": "ENCHANTED_SEEDS",
    "Enchanted Bone Meal": "ENCHANTED_BONE_MEAL",
    "Enchantment Experience 5": "ENCHANTMENT_EXPERIENCE_5",
    "Enchanted Bone Block": "ENCHANTED_BONE_BLOCK",
    "Small Enchanted Chest": "SMALL_ENCHANTED_CHEST",
    "Omega Egg": "OMEGA_EGG",
    "Purple Candy": "PURPLE_CANDY",
    "Enchantment Experience 2": "ENCHANTMENT_EXPERIENCE_2",
    "Polished Pumpkin": "POLISHED_PUMPKIN",
    "Enchantment Experience 1": "ENCHANTMENT_EXPERIENCE_1",
    "Enchantment Experience 4": "ENCHANTMENT_EXPERIENCE_4",
    "Enchantment Experience 3": "ENCHANTMENT_EXPERIENCE_3",
    "Enchanted Gold Block": "ENCHANTED_GOLD_BLOCK",
    "Fine Opal Gem": "FINE_OPAL_GEM",
    "Enchanted Flint": "ENCHANTED_FLINT",
    "Scorched Power Crystal": "SCORCHED_POWER_CRYSTAL",
    "Scarf Fragment": "SCARF_FRAGMENT",
    "Reheated Gummy Polar Bear": "REHEATED_GUMMY_POLAR_BEAR",
    Furball: "FURBALL",
    "Essence Spider": "ESSENCE_SPIDER",
    "Enchanted Clay Ball": "ENCHANTED_CLAY_BALL",
    "Glowstone Dust": "GLOWSTONE_DUST",
    "Flycatcher Upgrade": "FLYCATCHER_UPGRADE",
    "Perfect Amethyst Gem": "PERFECT_AMETHYST_GEM",
    "Implosion Scroll": "IMPLOSION_SCROLL",
    "Ftx 3070": "FTX_3070",
    Cropie: "CROPIE",
    "Pet Item Vampire Fang": "PET_ITEM_VAMPIRE_FANG",
    "Endstone Geode": "ENDSTONE_GEODE",
    "Great Carrot Candy": "GREAT_CARROT_CANDY",
    "Enchantment Mana Vampire 10": "ENCHANTMENT_MANA_VAMPIRE_10",
    "Enchanted Bone": "ENCHANTED_BONE",
    "Optical Lens": "OPTICAL_LENS",
    "Lava Water Orb": "LAVA_WATER_ORB",
    "Enchanted Diamond Block": "ENCHANTED_DIAMOND_BLOCK",
    "Enchantment Delicate 5": "ENCHANTMENT_DELICATE_5",
    "Goblin Egg Green": "GOBLIN_EGG_GREEN",
    "Enchantment Prosecute 6": "ENCHANTMENT_PROSECUTE_6",
    "Enchantment Caster 1": "ENCHANTMENT_CASTER_1",
    "Enchantment Prosecute 5": "ENCHANTMENT_PROSECUTE_5",
    "Enchantment Caster 2": "ENCHANTMENT_CASTER_2",
    "Giant Fragment Bigfoot": "GIANT_FRAGMENT_BIGFOOT",
    "Light Bait": "LIGHT_BAIT",
    "Hot Potato Book": "HOT_POTATO_BOOK",
    "Magic Mushroom Soup": "MAGIC_MUSHROOM_SOUP",
    "Enchantment Caster 3": "ENCHANTMENT_CASTER_3",
    "Clay Ball": "CLAY_BALL",
    "Enchantment Caster 4": "ENCHANTMENT_CASTER_4",
    "Enchantment Caster 5": "ENCHANTMENT_CASTER_5",
    "Old Fragment": "OLD_FRAGMENT",
    "Enchantment Caster 6": "ENCHANTMENT_CASTER_6",
    "Beating Heart": "BEATING_HEART",
    "Rough Amber Gem": "ROUGH_AMBER_GEM",
    "Enchantment Prosecute 4": "ENCHANTMENT_PROSECUTE_4",
    "Enchantment Prosecute 3": "ENCHANTMENT_PROSECUTE_3",
    "Enchantment Prosecute 2": "ENCHANTMENT_PROSECUTE_2",
    "Enchantment Prosecute 1": "ENCHANTMENT_PROSECUTE_1",
    "Amalgamated Crimsonite": "AMALGAMATED_CRIMSONITE",
    "Fine Amber Gem": "FINE_AMBER_GEM",
    "Super Magic Mushroom Soup": "SUPER_MAGIC_MUSHROOM_SOUP",
    "Enchanted Quartz": "ENCHANTED_QUARTZ",
    "Enchanted Coal Block": "ENCHANTED_COAL_BLOCK",
    "Ender Pearl": "ENDER_PEARL",
    "Lesser Soulflow Engine": "LESSER_SOULFLOW_ENGINE",
    "Large Walnut": "LARGE_WALNUT",
    "Flawed Jade Gem": "FLAWED_JADE_GEM",
    "Toil Log": "TOIL_LOG",
    "Sludge Juice": "SLUDGE_JUICE",
    "Bonzo Fragment": "BONZO_FRAGMENT",
    "Sugar Cane": "SUGAR_CANE",
    "Enchantment Respite 5": "ENCHANTMENT_RESPITE_5",
    "Enchantment Respite 3": "ENCHANTMENT_RESPITE_3",
    "Enchantment Respite 4": "ENCHANTMENT_RESPITE_4",
    "Enchantment Respite 1": "ENCHANTMENT_RESPITE_1",
    "Enchantment Respite 2": "ENCHANTMENT_RESPITE_2",
    "Tessellated Ender Pearl": "TESSELLATED_ENDER_PEARL",
    "Enchanted Raw Beef": "ENCHANTED_RAW_BEEF",
    "Aote Stone": "AOTE_STONE",
    "Rabbit Hide": "RABBIT_HIDE",
    "Inferno Fuel Block": "INFERNO_FUEL_BLOCK",
    "Enchantment Overload 5": "ENCHANTMENT_OVERLOAD_5",
    "Enchantment Overload 4": "ENCHANTMENT_OVERLOAD_4",
    "Enchantment Overload 3": "ENCHANTMENT_OVERLOAD_3",
    "Enchantment Overload 2": "ENCHANTMENT_OVERLOAD_2",
    "Enchantment Overload 1": "ENCHANTMENT_OVERLOAD_1",
    "Dark Bait": "DARK_BAIT",
    "Enchanted Pumpkin": "ENCHANTED_PUMPKIN",
    "Enchanted Cooked Fish": "ENCHANTED_COOKED_FISH",
    Obsidian: "OBSIDIAN",
    "Pet Item Exp Share Drop": "PET_ITEM_EXP_SHARE_DROP",
    Starfall: "STARFALL",
    "Second Master Star": "SECOND_MASTER_STAR",
    "Enchantment Fire Protection 6": "ENCHANTMENT_FIRE_PROTECTION_6",
    "Enchantment Fire Protection 5": "ENCHANTMENT_FIRE_PROTECTION_5",
    "Enchantment Fire Protection 7": "ENCHANTMENT_FIRE_PROTECTION_7",
    "Enchantment Hardened Mana 10": "ENCHANTMENT_HARDENED_MANA_10",
    "Enchantment Ultimate Jerry 2": "ENCHANTMENT_ULTIMATE_JERRY_2",
    "Entropy Suppressor": "ENTROPY_SUPPRESSOR",
    "Enchantment Ultimate Rend 3": "ENCHANTMENT_ULTIMATE_REND_3",
    "Enchantment Ultimate Jerry 1": "ENCHANTMENT_ULTIMATE_JERRY_1",
    "Enchantment Ultimate Rend 2": "ENCHANTMENT_ULTIMATE_REND_2",
    "Enchantment Ultimate Rend 1": "ENCHANTMENT_ULTIMATE_REND_1",
    "Glowstone Dust Distillate": "GLOWSTONE_DUST_DISTILLATE",
    "Enchanted Poppy": "ENCHANTED_POPPY",
    "Enchantment Ultimate Jerry 5": "ENCHANTMENT_ULTIMATE_JERRY_5",
    "Enchantment Ultimate Rend 5": "ENCHANTMENT_ULTIMATE_REND_5",
    "Enchantment Ultimate Jerry 4": "ENCHANTMENT_ULTIMATE_JERRY_4",
    "Enchantment Ultimate Jerry 3": "ENCHANTMENT_ULTIMATE_JERRY_3",
    "Enchantment Ultimate Rend 4": "ENCHANTMENT_ULTIMATE_REND_4",
    "Enchantment Fire Protection 2": "ENCHANTMENT_FIRE_PROTECTION_2",
    "Enchantment Fire Protection 1": "ENCHANTMENT_FIRE_PROTECTION_1",
    "Bazaar Cookie": "BAZAAR_COOKIE",
    "Enchantment Fire Protection 4": "ENCHANTMENT_FIRE_PROTECTION_4",
    "Enchantment Fire Protection 3": "ENCHANTMENT_FIRE_PROTECTION_3",
    "Brown Mushroom": "BROWN_MUSHROOM",
    "Displaced Leech": "DISPLACED_LEECH",
    "Enchantment Harvesting 5": "ENCHANTMENT_HARVESTING_5",
    "Enchantment Harvesting 4": "ENCHANTMENT_HARVESTING_4",
    "Enchantment Harvesting 3": "ENCHANTMENT_HARVESTING_3",
    "Carrot Item": "CARROT_ITEM",
    "Enchantment Harvesting 2": "ENCHANTMENT_HARVESTING_2",
    "Enchantment Harvesting 1": "ENCHANTMENT_HARVESTING_1",
    "Exp Bottle": "EXP_BOTTLE",
    "Molten Cube": "MOLTEN_CUBE",
    "Healing Tissue": "HEALING_TISSUE",
    "Enchantment Harvesting 6": "ENCHANTMENT_HARVESTING_6",
    "Enchanted Rabbit Hide": "ENCHANTED_RABBIT_HIDE",
    "Water Orb": "WATER_ORB",
    "Glacite Jewel": "GLACITE_JEWEL",
    "Inferno Vertex": "INFERNO_VERTEX",
    "Rusty Anchor": "RUSTY_ANCHOR",
    "Weak Wolf Catalyst": "WEAK_WOLF_CATALYST",
    "Flawed Amethyst Gem": "FLAWED_AMETHYST_GEM",
    "Perfect Jade Gem": "PERFECT_JADE_GEM",
    "Enchanted Birch Log": "ENCHANTED_BIRCH_LOG",
    "Fourth Master Star": "FOURTH_MASTER_STAR",
    "Enchanted Gunpowder": "ENCHANTED_GUNPOWDER",
    "Refined Amber": "REFINED_AMBER",
    "Enchanted Sugar": "ENCHANTED_SUGAR",
    Cactus: "CACTUS",
    "Enchanted Raw Salmon": "ENCHANTED_RAW_SALMON",
    "Bobbin Scriptures": "BOBBIN_SCRIPTURES",
    "Enchanted Emerald": "ENCHANTED_EMERALD",
    "Red Mushroom": "RED_MUSHROOM",
    "Grand Exp Bottle": "GRAND_EXP_BOTTLE",
    Mutton: "MUTTON",
    "Enchantment Dedication 2": "ENCHANTMENT_DEDICATION_2",
    "Enchantment Dedication 1": "ENCHANTMENT_DEDICATION_1",
    "Enchantment Dedication 4": "ENCHANTMENT_DEDICATION_4",
    "Enchantment Dedication 3": "ENCHANTMENT_DEDICATION_3",
    "Enchantment Ultimate Wise 2": "ENCHANTMENT_ULTIMATE_WISE_2",
    "Enchantment Ultimate Wise 1": "ENCHANTMENT_ULTIMATE_WISE_1",
    "Spider Eye": "SPIDER_EYE",
    "Enchantment Ultimate Wise 4": "ENCHANTMENT_ULTIMATE_WISE_4",
    "Enchantment Ultimate Wise 3": "ENCHANTMENT_ULTIMATE_WISE_3",
    "Bejeweled Handle": "BEJEWELED_HANDLE",
    "Large Enchanted Chest": "LARGE_ENCHANTED_CHEST",
    "Enchanted Netherrack": "ENCHANTED_NETHERRACK",
    Jaderald: "JADERALD",
    "Enchantment True Protection 1": "ENCHANTMENT_TRUE_PROTECTION_1",
    "Corrupt Soil": "CORRUPT_SOIL",
    "Prismarine Crystals": "PRISMARINE_CRYSTALS",
    "Rare Diamond": "RARE_DIAMOND",
    Ice: "ICE",
    "Tiger Shark Tooth": "TIGER_SHARK_TOOTH",
    "Enchantment Luck Of The Sea 4": "ENCHANTMENT_LUCK_OF_THE_SEA_4",
    "Enchantment Luck Of The Sea 5": "ENCHANTMENT_LUCK_OF_THE_SEA_5",
    "Enchantment Luck Of The Sea 6": "ENCHANTMENT_LUCK_OF_THE_SEA_6",
    "Enchantment Smarty Pants 3": "ENCHANTMENT_SMARTY_PANTS_3",
    "Enchantment Ultimate Wise 5": "ENCHANTMENT_ULTIMATE_WISE_5",
    "Enchantment Smarty Pants 2": "ENCHANTMENT_SMARTY_PANTS_2",
    "Enchantment Luck Of The Sea 1": "ENCHANTMENT_LUCK_OF_THE_SEA_1",
    "Enchantment Smarty Pants 5": "ENCHANTMENT_SMARTY_PANTS_5",
    "Enchantment Luck Of The Sea 2": "ENCHANTMENT_LUCK_OF_THE_SEA_2",
    "Enchantment Smarty Pants 4": "ENCHANTMENT_SMARTY_PANTS_4",
    "Enchantment Luck Of The Sea 3": "ENCHANTMENT_LUCK_OF_THE_SEA_3",
    "Golden Tooth": "GOLDEN_TOOTH",
    "The Art Of Peace": "THE_ART_OF_PEACE",
    "Enchantment Smarty Pants 1": "ENCHANTMENT_SMARTY_PANTS_1",
    "Hyper Catalyst": "HYPER_CATALYST",
    Volta: "VOLTA",
    "Rabbit Foot": "RABBIT_FOOT",
    "Superlite Motor": "SUPERLITE_MOTOR",
    Redstone: "REDSTONE",
    "Braided Griffin Feather": "BRAIDED_GRIFFIN_FEATHER",
    "Spirit Wing": "SPIRIT_WING",
    "Spooky Water Orb": "SPOOKY_WATER_ORB",
    "The Art Of War": "THE_ART_OF_WAR",
    "Enchantment Lure 2": "ENCHANTMENT_LURE_2",
    "Enchantment Lure 1": "ENCHANTMENT_LURE_1",
    "Enchantment Lure 6": "ENCHANTMENT_LURE_6",
    "Slime Ball": "SLIME_BALL",
    "Enchantment Lure 5": "ENCHANTMENT_LURE_5",
    "Enchantment Lure 4": "ENCHANTMENT_LURE_4",
    "Enchantment Lure 3": "ENCHANTMENT_LURE_3",
    "Snow Ball": "SNOW_BALL",
    "Holy Fragment": "HOLY_FRAGMENT",
    "Enchanted Wool": "ENCHANTED_WOOL",
    "Enchanted Egg": "ENCHANTED_EGG",
    "Superb Carrot Candy": "SUPERB_CARROT_CANDY",
    "Enchantment Ferocious Mana 8": "ENCHANTMENT_FEROCIOUS_MANA_8",
    "Enchantment Ferocious Mana 9": "ENCHANTMENT_FEROCIOUS_MANA_9",
    "Fine Jade Gem": "FINE_JADE_GEM",
    "Enchantment Ferocious Mana 4": "ENCHANTMENT_FEROCIOUS_MANA_4",
    "Flawed Ruby Gem": "FLAWED_RUBY_GEM",
    "Enchantment Magnet 2": "ENCHANTMENT_MAGNET_2",
    "Raw Chicken": "RAW_CHICKEN",
    "Enchantment Ferocious Mana 5": "ENCHANTMENT_FEROCIOUS_MANA_5",
    "Enchantment Magnet 1": "ENCHANTMENT_MAGNET_1",
    Sorrow: "SORROW",
    "Enchantment Ferocious Mana 6": "ENCHANTMENT_FEROCIOUS_MANA_6",
    "Enchantment Magnet 4": "ENCHANTMENT_MAGNET_4",
    "Enchantment Ferocious Mana 7": "ENCHANTMENT_FEROCIOUS_MANA_7",
    "Enchantment Magnet 3": "ENCHANTMENT_MAGNET_3",
    "Flawless Jasper Gem": "FLAWLESS_JASPER_GEM",
    "Enchantment Magnet 6": "ENCHANTMENT_MAGNET_6",
    "Enchantment Ferocious Mana 1": "ENCHANTMENT_FEROCIOUS_MANA_1",
    "Enchantment Magnet 5": "ENCHANTMENT_MAGNET_5",
    "Enchantment Ferocious Mana 2": "ENCHANTMENT_FEROCIOUS_MANA_2",
    "Enchantment Ferocious Mana 3": "ENCHANTMENT_FEROCIOUS_MANA_3",
    "Lush Berberis": "LUSH_BERBERIS",
    "Enchantment Projectile Protection 7":
        "ENCHANTMENT_PROJECTILE_PROTECTION_7",
    "Enchantment Champion 10": "ENCHANTMENT_CHAMPION_10",
    "Enchantment Projectile Protection 6":
        "ENCHANTMENT_PROJECTILE_PROTECTION_6",
    "Enchanted Shark Fin": "ENCHANTED_SHARK_FIN",
    "Enchantment Projectile Protection 5":
        "ENCHANTMENT_PROJECTILE_PROTECTION_5",
    "Enchantment Projectile Protection 4":
        "ENCHANTMENT_PROJECTILE_PROTECTION_4",
    "Enchantment Projectile Protection 3":
        "ENCHANTMENT_PROJECTILE_PROTECTION_3",
    "Enchantment Projectile Protection 2":
        "ENCHANTMENT_PROJECTILE_PROTECTION_2",
    "Enchantment Projectile Protection 1":
        "ENCHANTMENT_PROJECTILE_PROTECTION_1",
    "Ink Sack": "INK_SACK",
    "Crystal Fragment": "CRYSTAL_FRAGMENT",
    "Enchanted Redstone Block": "ENCHANTED_REDSTONE_BLOCK",
    "Inferno Apex": "INFERNO_APEX",
    "Enchanted Redstone Lamp": "ENCHANTED_REDSTONE_LAMP",
    Treasurite: "TREASURITE",
    "Perfect Opal Gem": "PERFECT_OPAL_GEM",
    Melon: "MELON",
    Diamonite: "DIAMONITE",
    "Glowing Mushroom": "GLOWING_MUSHROOM",
    "Enchantment Dragon Hunter 4": "ENCHANTMENT_DRAGON_HUNTER_4",
    "Enchantment Dragon Hunter 3": "ENCHANTMENT_DRAGON_HUNTER_3",
    "Enchantment Dragon Hunter 5": "ENCHANTMENT_DRAGON_HUNTER_5",
    "Enchanted Iron Block": "ENCHANTED_IRON_BLOCK",
    "Enchantment Dragon Hunter 2": "ENCHANTMENT_DRAGON_HUNTER_2",
    Bone: "BONE",
    "Enchantment Dragon Hunter 1": "ENCHANTMENT_DRAGON_HUNTER_1",
    "Poisonous Potato": "POISONOUS_POTATO",
    "Kismet Feather": "KISMET_FEATHER",
    "Revenant Flesh": "REVENANT_FLESH",
    "Enchanted Glowstone": "ENCHANTED_GLOWSTONE",
    "Obsidian Tablet": "OBSIDIAN_TABLET",
    "Essence Wither": "ESSENCE_WITHER",
    "Enchantment Charm 2": "ENCHANTMENT_CHARM_2",
    "Enchantment Charm 3": "ENCHANTMENT_CHARM_3",
    "Enchantment Charm 1": "ENCHANTMENT_CHARM_1",
    "Blaze Rod": "BLAZE_ROD",
    "Enchantment Charm 4": "ENCHANTMENT_CHARM_4",
    "Young Fragment": "YOUNG_FRAGMENT",
    "Enchantment Charm 5": "ENCHANTMENT_CHARM_5",
    "Mithril Plate": "MITHRIL_PLATE",
    "Refined Mineral": "REFINED_MINERAL",
    Chyme: "CHYME",
    "Divan Fragment": "DIVAN_FRAGMENT",
    "Rough Ruby Gem": "ROUGH_RUBY_GEM",
    "Enchantment Impaling 3": "ENCHANTMENT_IMPALING_3",
    "Enchantment Impaling 2": "ENCHANTMENT_IMPALING_2",
    "Goblin Egg Blue": "GOBLIN_EGG_BLUE",
    "Enchantment Impaling 1": "ENCHANTMENT_IMPALING_1",
    Catalyst: "CATALYST",
    "Enchanted Ink Sack": "ENCHANTED_INK_SACK",
    "Jerry Stone": "JERRY_STONE",
    "Molten Powder": "MOLTEN_POWDER",
    "Flawless Sapphire Gem": "FLAWLESS_SAPPHIRE_GEM",
    "Magma Urchin": "MAGMA_URCHIN",
    "Jacobs Ticket": "JACOBS_TICKET",
    "Bat Firework": "BAT_FIREWORK",
    "Enchantment Quantum 4": "ENCHANTMENT_QUANTUM_4",
    "Enchantment Quantum 5": "ENCHANTMENT_QUANTUM_5",
    "Absolute Ender Pearl": "ABSOLUTE_ENDER_PEARL",
    "Enchantment Replenish 1": "ENCHANTMENT_REPLENISH_1",
    "Enchantment Quantum 3": "ENCHANTMENT_QUANTUM_3",
    "Enchanted Ender Pearl": "ENCHANTED_ENDER_PEARL",
    "Arrow Bundle Magma": "ARROW_BUNDLE_MAGMA",
    "Spiked Bait": "SPIKED_BAIT",
    "Enchanted Fermented Spider Eye": "ENCHANTED_FERMENTED_SPIDER_EYE",
    "Blessed Fruit": "BLESSED_FRUIT",
    "Enchantment Ultimate Swarm 5": "ENCHANTMENT_ULTIMATE_SWARM_5",
    "Enchantment Turbo Wheat 3": "ENCHANTMENT_TURBO_WHEAT_3",
    "Enchantment Turbo Wheat 4": "ENCHANTMENT_TURBO_WHEAT_4",
    "Enchantment Silk Touch 1": "ENCHANTMENT_SILK_TOUCH_1",
    "Enchantment Turbo Wheat 1": "ENCHANTMENT_TURBO_WHEAT_1",
    "Enchantment Turbo Wheat 2": "ENCHANTMENT_TURBO_WHEAT_2",
    "Enchantment Ultimate Swarm 3": "ENCHANTMENT_ULTIMATE_SWARM_3",
    "Enchantment Ultimate Swarm 4": "ENCHANTMENT_ULTIMATE_SWARM_4",
    "Enchantment Ultimate Swarm 1": "ENCHANTMENT_ULTIMATE_SWARM_1",
    "Enchantment Turbo Wheat 5": "ENCHANTMENT_TURBO_WHEAT_5",
    "Exportable Carrots": "EXPORTABLE_CARROTS",
    "Enchantment Ultimate Swarm 2": "ENCHANTMENT_ULTIMATE_SWARM_2",
    "Null Ovoid": "NULL_OVOID",
    "Gold Ingot": "GOLD_INGOT",
    "Enchantment Sugar Rush 3": "ENCHANTMENT_SUGAR_RUSH_3",
    "Enchantment Sugar Rush 2": "ENCHANTMENT_SUGAR_RUSH_2",
    "Enchanted Iron": "ENCHANTED_IRON",
    "Enchantment Sugar Rush 1": "ENCHANTMENT_SUGAR_RUSH_1",
    "Enchanted Hay Block": "ENCHANTED_HAY_BLOCK",
    Hemovibe: "HEMOVIBE",
    "Enchanted Titanium": "ENCHANTED_TITANIUM",
    "Spooky Bait": "SPOOKY_BAIT",
    Emerald: "EMERALD",
    "Twilight Arrow Poison": "TWILIGHT_ARROW_POISON",
    "Enchanted Rabbit Foot": "ENCHANTED_RABBIT_FOOT",
    "Potato Spreading": "POTATO_SPREADING",
    "Enchanted Ice": "ENCHANTED_ICE",
    "Arachne Keeper Fragment": "ARACHNE_KEEPER_FRAGMENT",
    "Enchantment Growth 1": "ENCHANTMENT_GROWTH_1",
    "Enchantment Growth 2": "ENCHANTMENT_GROWTH_2",
    "Green Gift": "GREEN_GIFT",
    "Enchantment Growth 3": "ENCHANTMENT_GROWTH_3",
    "Enchantment Growth 4": "ENCHANTMENT_GROWTH_4",
    "Enchantment Growth 5": "ENCHANTMENT_GROWTH_5",
    "Enchantment Growth 6": "ENCHANTMENT_GROWTH_6",
    "Red Nose": "RED_NOSE",
    "Flawless Amethyst Gem": "FLAWLESS_AMETHYST_GEM",
    "Null Edge": "NULL_EDGE",
    "Enchantment Growth 7": "ENCHANTMENT_GROWTH_7",
    "Packed Ice": "PACKED_ICE",
    "Yellow Flower": "YELLOW_FLOWER",
    "Revenant Catalyst": "REVENANT_CATALYST",
    "Wither Catalyst": "WITHER_CATALYST",
    "Hamster Wheel": "HAMSTER_WHEEL",
    "Enchanted Coal": "ENCHANTED_COAL",
    "Magma Fish Silver": "MAGMA_FISH_SILVER",
    "Flawless Opal Gem": "FLAWLESS_OPAL_GEM",
    "Sulphuric Coal": "SULPHURIC_COAL",
    "Essence Undead": "ESSENCE_UNDEAD",
    "Dragon Claw": "DRAGON_CLAW",
    "Daedalus Stick": "DAEDALUS_STICK",
    "Enchantment Ultimate Chimera 1": "ENCHANTMENT_ULTIMATE_CHIMERA_1",
    "Enchantment Ultimate Last Stand 5": "ENCHANTMENT_ULTIMATE_LAST_STAND_5",
    "Enchantment Ultimate Last Stand 4": "ENCHANTMENT_ULTIMATE_LAST_STAND_4",
    "Enchantment Ultimate Last Stand 3": "ENCHANTMENT_ULTIMATE_LAST_STAND_3",
    "Enchantment Ultimate Chimera 5": "ENCHANTMENT_ULTIMATE_CHIMERA_5",
    "Enchantment Ultimate Last Stand 2": "ENCHANTMENT_ULTIMATE_LAST_STAND_2",
    "Enchantment Ultimate Chimera 4": "ENCHANTMENT_ULTIMATE_CHIMERA_4",
    "Enchantment Ultimate Last Stand 1": "ENCHANTMENT_ULTIMATE_LAST_STAND_1",
    "Enchantment Ultimate Chimera 3": "ENCHANTMENT_ULTIMATE_CHIMERA_3",
    "Enchantment Ultimate Chimera 2": "ENCHANTMENT_ULTIMATE_CHIMERA_2",
    "Lucky Dice": "LUCKY_DICE",
    "Foul Flesh": "FOUL_FLESH",
    "Raw Beef": "RAW_BEEF",
    "Enchanted Eye Of Ender": "ENCHANTED_EYE_OF_ENDER",
    Ectoplasm: "ECTOPLASM",
    "Precious Pearl": "PRECIOUS_PEARL",
    "Enchanted Mycelium": "ENCHANTED_MYCELIUM",
    Rabbit: "RABBIT",
    "Magma Fish Diamond": "MAGMA_FISH_DIAMOND",
    "Enchanted Hopper": "ENCHANTED_HOPPER",
    "Griffin Feather": "GRIFFIN_FEATHER",
    Hemobomb: "HEMOBOMB",
    "Giant Fragment Diamond": "GIANT_FRAGMENT_DIAMOND",
    Soulflow: "SOULFLOW",
    "Minnow Bait": "MINNOW_BAIT",
    "Enchanted Magma Cream": "ENCHANTED_MAGMA_CREAM",
    "Enchanted Firework Rocket": "ENCHANTED_FIREWORK_ROCKET",
    "Blaze Wax": "BLAZE_WAX",
    "Wither Blood": "WITHER_BLOOD",
    "Enchantment Efficiency 5": "ENCHANTMENT_EFFICIENCY_5",
    "Enchantment Efficiency 4": "ENCHANTMENT_EFFICIENCY_4",
    "Chocolate Chip": "CHOCOLATE_CHIP",
    "Enchantment Efficiency 3": "ENCHANTMENT_EFFICIENCY_3",
    "Enchantment Efficiency 2": "ENCHANTMENT_EFFICIENCY_2",
    "Flawless Jade Gem": "FLAWLESS_JADE_GEM",
    "Hard Stone": "HARD_STONE",
    "Enchantment Efficiency 1": "ENCHANTMENT_EFFICIENCY_1",
    "Superboom Tnt": "SUPERBOOM_TNT",
    "Enchanted Cooked Mutton": "ENCHANTED_COOKED_MUTTON",
    "Enchantment Efficiency 9": "ENCHANTMENT_EFFICIENCY_9",
    "Enchantment Efficiency 8": "ENCHANTMENT_EFFICIENCY_8",
    "Refined Titanium": "REFINED_TITANIUM",
    "Enchantment Efficiency 7": "ENCHANTMENT_EFFICIENCY_7",
    "Enchantment Feather Falling 10": "ENCHANTMENT_FEATHER_FALLING_10",
    "Enchantment Efficiency 6": "ENCHANTMENT_EFFICIENCY_6",
    "Enchantment Smoldering 5": "ENCHANTMENT_SMOLDERING_5",
    "Shiny Prism": "SHINY_PRISM",
    "Enchantment Smoldering 3": "ENCHANTMENT_SMOLDERING_3",
    "Enchantment Smoldering 4": "ENCHANTMENT_SMOLDERING_4",
    "Enchantment Smoldering 1": "ENCHANTMENT_SMOLDERING_1",
    "First Master Star": "FIRST_MASTER_STAR",
    "Enchantment Smoldering 2": "ENCHANTMENT_SMOLDERING_2",
    "Flowering Bouquet": "FLOWERING_BOUQUET",
    "Spirit Leap": "SPIRIT_LEAP",
    "Fine Jasper Gem": "FINE_JASPER_GEM",
    "Enchanted Charcoal": "ENCHANTED_CHARCOAL",
    "Book Of Stats": "BOOK_OF_STATS",
    "Simple Carrot Candy": "SIMPLE_CARROT_CANDY",
    "Enchanted Diamond": "ENCHANTED_DIAMOND",
    "Enchantment Feather Falling 20": "ENCHANTMENT_FEATHER_FALLING_20",
    "Oil Barrel": "OIL_BARREL",
    "Golem Poppy": "GOLEM_POPPY",
    "Horns Of Torment": "HORNS_OF_TORMENT",
    "Enchantment Critical 6": "ENCHANTMENT_CRITICAL_6",
    "Jerry Box Green": "JERRY_BOX_GREEN",
    "Farming For Dummies": "FARMING_FOR_DUMMIES",
    "Enchantment Critical 7": "ENCHANTMENT_CRITICAL_7",
    "Enchantment Critical 4": "ENCHANTMENT_CRITICAL_4",
    "Enchantment Critical 5": "ENCHANTMENT_CRITICAL_5",
    "Enchantment Critical 2": "ENCHANTMENT_CRITICAL_2",
    "Enchanted Golden Carrot": "ENCHANTED_GOLDEN_CARROT",
    "Enchantment Critical 3": "ENCHANTMENT_CRITICAL_3",
    "Enchantment Critical 1": "ENCHANTMENT_CRITICAL_1",
    "Enchantment Aiming 1": "ENCHANTMENT_AIMING_1",
    "Enchantment Aiming 2": "ENCHANTMENT_AIMING_2",
    "Enchantment Aiming 3": "ENCHANTMENT_AIMING_3",
    "Enchantment Aiming 4": "ENCHANTMENT_AIMING_4",
    "Enchantment Aiming 5": "ENCHANTMENT_AIMING_5",
    "Shadow Warp Scroll": "SHADOW_WARP_SCROLL",
    "Enchantment Ultimate Habanero Tactics 4":
        "ENCHANTMENT_ULTIMATE_HABANERO_TACTICS_4",
    "Enchantment Frost Walker 2": "ENCHANTMENT_FROST_WALKER_2",
    "Enchantment Thunderbolt 6": "ENCHANTMENT_THUNDERBOLT_6",
    "Enchantment Blast Protection 7": "ENCHANTMENT_BLAST_PROTECTION_7",
    "Enchanted Mycelium Cube": "ENCHANTED_MYCELIUM_CUBE",
    "Flawed Jasper Gem": "FLAWED_JASPER_GEM",
    "Enchantment Ultimate Habanero Tactics 5":
        "ENCHANTMENT_ULTIMATE_HABANERO_TACTICS_5",
    "Enchantment Frost Walker 1": "ENCHANTMENT_FROST_WALKER_1",
    "Enchantment Thunderbolt 1": "ENCHANTMENT_THUNDERBOLT_1",
    "Glacial Fragment": "GLACIAL_FRAGMENT",
    "Enchanted Poisonous Potato": "ENCHANTED_POISONOUS_POTATO",
    "Flawed Amber Gem": "FLAWED_AMBER_GEM",
    "Enchantment Thunderbolt 4": "ENCHANTMENT_THUNDERBOLT_4",
    "Enchantment Thunderbolt 5": "ENCHANTMENT_THUNDERBOLT_5",
    "Enchantment Thunderbolt 2": "ENCHANTMENT_THUNDERBOLT_2",
    "Enchantment Thunderbolt 3": "ENCHANTMENT_THUNDERBOLT_3",
    "Enchantment Ultimate Reiterate 1": "ENCHANTMENT_ULTIMATE_REITERATE_1",
    "Enchantment Ultimate Reiterate 4": "ENCHANTMENT_ULTIMATE_REITERATE_4",
    "Enchantment Compact 10": "ENCHANTMENT_COMPACT_10",
    "Enchantment Ultimate Reiterate 5": "ENCHANTMENT_ULTIMATE_REITERATE_5",
    "Enchantment Ultimate Reiterate 2": "ENCHANTMENT_ULTIMATE_REITERATE_2",
    "Prismarine Shard": "PRISMARINE_SHARD",
    "Enchantment Ultimate Reiterate 3": "ENCHANTMENT_ULTIMATE_REITERATE_3",
    "Synthetic Heart": "SYNTHETIC_HEART",
    "Power Crystal": "POWER_CRYSTAL",
    "Wise Fragment": "WISE_FRAGMENT",
    "Shark Fin": "SHARK_FIN",
    "Refined Mithril": "REFINED_MITHRIL",
    "Xxlarge Enchanted Chest": "XXLARGE_ENCHANTED_CHEST",
    "Fuel Tank": "FUEL_TANK",
    "Jalapeno Book": "JALAPENO_BOOK",
    "Enchantment Venomous 3": "ENCHANTMENT_VENOMOUS_3",
    "Potato Item": "POTATO_ITEM",
    "Enchantment Venomous 4": "ENCHANTMENT_VENOMOUS_4",
    "Enchantment Venomous 5": "ENCHANTMENT_VENOMOUS_5",
    "Skymart Brochure": "SKYMART_BROCHURE",
    "Enchanted Huge Mushroom 1": "ENCHANTED_HUGE_MUSHROOM_1",
    "Enchantment Venomous 6": "ENCHANTMENT_VENOMOUS_6",
    "Presumed Gallon Of Red Paint": "PRESUMED_GALLON_OF_RED_PAINT",
    Hemoglass: "HEMOGLASS",
    "Enchantment Venomous 1": "ENCHANTMENT_VENOMOUS_1",
    "Enchantment Venomous 2": "ENCHANTMENT_VENOMOUS_2",
    "Electron Transmitter": "ELECTRON_TRANSMITTER",
    "Enchanted Cobblestone": "ENCHANTED_COBBLESTONE",
    "Enchantment Strong Mana 10": "ENCHANTMENT_STRONG_MANA_10",
    "Enchanted Huge Mushroom 2": "ENCHANTED_HUGE_MUSHROOM_2",
    "Glowy Chum Bait": "GLOWY_CHUM_BAIT",
    "Stuffed Chili Pepper": "STUFFED_CHILI_PEPPER",
    "Budget Hopper": "BUDGET_HOPPER",
    "Ice Bait": "ICE_BAIT",
    "Terry Snowglobe": "TERRY_SNOWGLOBE",
    "Cheese Fuel": "CHEESE_FUEL",
    "Kuudra Mandible": "KUUDRA_MANDIBLE",
    "Enchantment Feather Falling 3": "ENCHANTMENT_FEATHER_FALLING_3",
    "Enchantment Feather Falling 2": "ENCHANTMENT_FEATHER_FALLING_2",
    "Pumpkin Guts": "PUMPKIN_GUTS",
    "Enchantment Feather Falling 1": "ENCHANTMENT_FEATHER_FALLING_1",
    "Enchantment Feather Falling 7": "ENCHANTMENT_FEATHER_FALLING_7",
    "Blaze Rod Distillate": "BLAZE_ROD_DISTILLATE",
    "Enchantment Feather Falling 6": "ENCHANTMENT_FEATHER_FALLING_6",
    "Wither Shield Scroll": "WITHER_SHIELD_SCROLL",
    "Enchantment Feather Falling 5": "ENCHANTMENT_FEATHER_FALLING_5",
    "Enchantment Feather Falling 4": "ENCHANTMENT_FEATHER_FALLING_4",
    "Enchantment Feather Falling 9": "ENCHANTMENT_FEATHER_FALLING_9",
    "Acacia Birdhouse": "ACACIA_BIRDHOUSE",
    "Enchantment Feather Falling 8": "ENCHANTMENT_FEATHER_FALLING_8",
    "Spider Catalyst": "SPIDER_CATALYST",
    "Enchanted Lapis Lazuli Block": "ENCHANTED_LAPIS_LAZULI_BLOCK",
    "Enchanted Endstone": "ENCHANTED_ENDSTONE",
    "Colossal Exp Bottle": "COLOSSAL_EXP_BOTTLE",
    "Enchanted Sand": "ENCHANTED_SAND",
    "Essence Ice": "ESSENCE_ICE",
    "Enchanted String": "ENCHANTED_STRING",
    "Moil Log": "MOIL_LOG",
    "Enchanted Dandelion": "ENCHANTED_DANDELION",
    "Mimic Fragment": "MIMIC_FRAGMENT",
    "Magma Fish Gold": "MAGMA_FISH_GOLD",
    "Soul Fragment": "SOUL_FRAGMENT",
    "Enchanted Lapis Lazuli": "ENCHANTED_LAPIS_LAZULI",
    "Enderman Cortex Rewriter": "ENDERMAN_CORTEX_REWRITER",
    "Melon Block": "MELON_BLOCK",
    "Crude Gabagool Distillate": "CRUDE_GABAGOOL_DISTILLATE",
    Seeds: "SEEDS",
    "Enchanted Leather": "ENCHANTED_LEATHER",
    "Enchanted Sponge": "ENCHANTED_SPONGE",
    "Wolf Tooth": "WOLF_TOOTH",
    "Enchanted Nether Stalk": "ENCHANTED_NETHER_STALK",
    "Enchantment Curse Of Vanishing 0": "ENCHANTMENT_CURSE_OF_VANISHING_0",
    "Enchanted Redstone": "ENCHANTED_REDSTONE",
    "Meteor Shard": "METEOR_SHARD",
    "Enchantment Compact 2": "ENCHANTMENT_COMPACT_2",
    "Enchantment Compact 3": "ENCHANTMENT_COMPACT_3",
    "Dwarven Compactor": "DWARVEN_COMPACTOR",
    "Enchantment Compact 1": "ENCHANTMENT_COMPACT_1",
    "Great White Shark Tooth": "GREAT_WHITE_SHARK_TOOTH",
    "Essence Gold": "ESSENCE_GOLD",
    "Enchantment Pristine 1": "ENCHANTMENT_PRISTINE_1",
    "Enchantment Compact 6": "ENCHANTMENT_COMPACT_6",
    "Enchantment Blast Protection 4": "ENCHANTMENT_BLAST_PROTECTION_4",
    "Enchantment Pristine 2": "ENCHANTMENT_PRISTINE_2",
    "Enchantment Compact 7": "ENCHANTMENT_COMPACT_7",
    "Enchantment Blast Protection 3": "ENCHANTMENT_BLAST_PROTECTION_3",
    "Recombobulator 3000": "RECOMBOBULATOR_3000",
    "Enchantment Blast Protection 6": "ENCHANTMENT_BLAST_PROTECTION_6",
    "Enchantment Compact 4": "ENCHANTMENT_COMPACT_4",
    "Enchantment Blast Protection 5": "ENCHANTMENT_BLAST_PROTECTION_5",
    "Enchantment Compact 5": "ENCHANTMENT_COMPACT_5",
    "Enchantment Pristine 5": "ENCHANTMENT_PRISTINE_5",
    "Enchantment Pristine 3": "ENCHANTMENT_PRISTINE_3",
    "Enchantment Compact 8": "ENCHANTMENT_COMPACT_8",
    "Enchantment Blast Protection 2": "ENCHANTMENT_BLAST_PROTECTION_2",
    "Enchantment Pristine 4": "ENCHANTMENT_PRISTINE_4",
    "Enchantment Compact 9": "ENCHANTMENT_COMPACT_9",
    "Enchantment Blast Protection 1": "ENCHANTMENT_BLAST_PROTECTION_1",
    "Enchantment Ferocious Mana 10": "ENCHANTMENT_FEROCIOUS_MANA_10",
    "Necromancer Brooch": "NECROMANCER_BROOCH",
    "Enchanted Pork": "ENCHANTED_PORK",
    "Pet Item Lucky Clover Drop": "PET_ITEM_LUCKY_CLOVER_DROP",
    "Burrowing Spores": "BURROWING_SPORES",
    "Deep Sea Orb": "DEEP_SEA_ORB",
    "Rough Jasper Gem": "ROUGH_JASPER_GEM",
    Feather: "FEATHER",
    "Petrified Starfall": "PETRIFIED_STARFALL",
    "Enchanted Red Sand": "ENCHANTED_RED_SAND",
    "Enchanted Clownfish": "ENCHANTED_CLOWNFISH",
    "Pitchin Koi": "PITCHIN_KOI",
    "Enchanted Gold": "ENCHANTED_GOLD",
    "Enchantment Life Steal 1": "ENCHANTMENT_LIFE_STEAL_1",
    "Enchantment Life Steal 2": "ENCHANTMENT_LIFE_STEAL_2",
    "Enchantment Smelting Touch 1": "ENCHANTMENT_SMELTING_TOUCH_1",
    "Enchantment Life Steal 5": "ENCHANTMENT_LIFE_STEAL_5",
    "Enchantment Life Steal 3": "ENCHANTMENT_LIFE_STEAL_3",
    "Enchantment Life Steal 4": "ENCHANTMENT_LIFE_STEAL_4",
    "Enchantment Piscary 1": "ENCHANTMENT_PISCARY_1",
    "Golden Plate": "GOLDEN_PLATE",
    "Enchantment Turbo Mushrooms 5": "ENCHANTMENT_TURBO_MUSHROOMS_5",
    "Sadan Brooch": "SADAN_BROOCH",
    "Fifth Master Star": "FIFTH_MASTER_STAR",
    "Enchantment Piscary 3": "ENCHANTMENT_PISCARY_3",
    "Enchantment Piscary 2": "ENCHANTMENT_PISCARY_2",
    "Enchanted Glowstone Dust": "ENCHANTED_GLOWSTONE_DUST",
    "Blue Ice Hunk": "BLUE_ICE_HUNK",
    "Enchantment Piscary 5": "ENCHANTMENT_PISCARY_5",
    "Enchantment Piscary 4": "ENCHANTMENT_PISCARY_4",
    "Enchantment Piscary 6": "ENCHANTMENT_PISCARY_6",
    "Enchantment Tabasco 1": "ENCHANTMENT_TABASCO_1",
    "Enchantment Tabasco 3": "ENCHANTMENT_TABASCO_3",
    "Enchantment Punch 1": "ENCHANTMENT_PUNCH_1",
    "Enchantment Tabasco 2": "ENCHANTMENT_TABASCO_2",
    "Enchanted Sugar Cane": "ENCHANTED_SUGAR_CANE",
    "Transmission Tuner": "TRANSMISSION_TUNER",
    "Enchantment Punch 2": "ENCHANTMENT_PUNCH_2",
    "Enchantment Turbo Mushrooms 2": "ENCHANTMENT_TURBO_MUSHROOMS_2",
    "Enchantment Turbo Mushrooms 1": "ENCHANTMENT_TURBO_MUSHROOMS_1",
    "Enchantment Turbo Mushrooms 4": "ENCHANTMENT_TURBO_MUSHROOMS_4",
    "Concentrated Stone": "CONCENTRATED_STONE",
    "Enchantment Turbo Mushrooms 3": "ENCHANTMENT_TURBO_MUSHROOMS_3",
    "Enchantment Mana Vampire 2": "ENCHANTMENT_MANA_VAMPIRE_2",
    "Enchantment Mana Vampire 1": "ENCHANTMENT_MANA_VAMPIRE_1",
    "Enchantment Mana Vampire 4": "ENCHANTMENT_MANA_VAMPIRE_4",
    "Enchantment Mana Vampire 3": "ENCHANTMENT_MANA_VAMPIRE_3",
    "Enchantment Mana Vampire 6": "ENCHANTMENT_MANA_VAMPIRE_6",
    "Enchantment Mana Vampire 5": "ENCHANTMENT_MANA_VAMPIRE_5",
    "Shark Water Orb": "SHARK_WATER_ORB",
    "Enchantment Mana Vampire 8": "ENCHANTMENT_MANA_VAMPIRE_8",
    "Enchantment Mana Vampire 7": "ENCHANTMENT_MANA_VAMPIRE_7",
    "Ghast Tear": "GHAST_TEAR",
    "Enchantment Mana Vampire 9": "ENCHANTMENT_MANA_VAMPIRE_9",
    "Unstable Fragment": "UNSTABLE_FRAGMENT",
    "Magma Cream Distillate": "MAGMA_CREAM_DISTILLATE",
    Corleonite: "CORLEONITE",
    "Enchanted Emerald Block": "ENCHANTED_EMERALD_BLOCK",
    "Subzero Inverter": "SUBZERO_INVERTER",
    "Giant Tooth": "GIANT_TOOTH",
    "Enchantment Piercing 1": "ENCHANTMENT_PIERCING_1",
    "Enchantment Ultimate The One 5": "ENCHANTMENT_ULTIMATE_THE_ONE_5",
    "Enchanted Mutton": "ENCHANTED_MUTTON",
    "Enchantment Titan Killer 7": "ENCHANTMENT_TITAN_KILLER_7",
    "Enchantment Titan Killer 6": "ENCHANTMENT_TITAN_KILLER_6",
    "Null Sphere": "NULL_SPHERE",
    "Enchantment Titan Killer 5": "ENCHANTMENT_TITAN_KILLER_5",
    "Enchantment Titan Killer 4": "ENCHANTMENT_TITAN_KILLER_4",
    "Enchantment Titan Killer 3": "ENCHANTMENT_TITAN_KILLER_3",
    "Enchantment Titan Killer 2": "ENCHANTMENT_TITAN_KILLER_2",
    "Enchantment Titan Killer 1": "ENCHANTMENT_TITAN_KILLER_1",
    "Stock Of Stonks": "STOCK_OF_STONKS",
    "Superior Fragment": "SUPERIOR_FRAGMENT",
    "Magma Bucket": "MAGMA_BUCKET",
    "Enchantment Ultimate The One 4": "ENCHANTMENT_ULTIMATE_THE_ONE_4",
    "Enchantment Power 1": "ENCHANTMENT_POWER_1",
    "Hot Bait": "HOT_BAIT",
    "Null Blade": "NULL_BLADE",
    "Enchantment Power 7": "ENCHANTMENT_POWER_7",
    "Enchantment Power 6": "ENCHANTMENT_POWER_6",
    "Enchantment Angler 1": "ENCHANTMENT_ANGLER_1",
    "Enchantment Angler 2": "ENCHANTMENT_ANGLER_2",
    "Worm Membrane": "WORM_MEMBRANE",
    "Enchantment Angler 3": "ENCHANTMENT_ANGLER_3",
    "Enchantment Power 3": "ENCHANTMENT_POWER_3",
    "Enchantment Angler 4": "ENCHANTMENT_ANGLER_4",
    "Enchantment Angler 5": "ENCHANTMENT_ANGLER_5",
    "Enchantment Power 2": "ENCHANTMENT_POWER_2",
    "Enchantment Angler 6": "ENCHANTMENT_ANGLER_6",
    "Enchantment Power 5": "ENCHANTMENT_POWER_5",
    "Enchantment Power 4": "ENCHANTMENT_POWER_4",
    "Water Lily": "WATER_LILY",
    "Enchantment Thorns 3": "ENCHANTMENT_THORNS_3",
    "Bob Omb": "BOB_OMB",
    "Log 2": "LOG_2",
    "Mithril Infusion": "MITHRIL_INFUSION",
    Coal: "COAL",
    "Enchantment Ultimate Bobbin Time 3": "ENCHANTMENT_ULTIMATE_BOBBIN_TIME_3",
    "Enchantment Ultimate Bobbin Time 4": "ENCHANTMENT_ULTIMATE_BOBBIN_TIME_4",
    "Enchantment Ultimate Bobbin Time 5": "ENCHANTMENT_ULTIMATE_BOBBIN_TIME_5",
    "Enchantment Thorns 1": "ENCHANTMENT_THORNS_1",
    "Enchantment Thorns 2": "ENCHANTMENT_THORNS_2",
    "Enchantment Vampirism 5": "ENCHANTMENT_VAMPIRISM_5",
    "Goblin Egg": "GOBLIN_EGG",
    "Enchanted Prismarine Crystals": "ENCHANTED_PRISMARINE_CRYSTALS",
    "Enchantment Vampirism 6": "ENCHANTMENT_VAMPIRISM_6",
    "Perfect Topaz Gem": "PERFECT_TOPAZ_GEM",
    "Livid Fragment": "LIVID_FRAGMENT",
    "Enchantment Vampirism 3": "ENCHANTMENT_VAMPIRISM_3",
    Plasma: "PLASMA",
    "Enchantment Vampirism 4": "ENCHANTMENT_VAMPIRISM_4",
    "Enchanted Wet Sponge": "ENCHANTED_WET_SPONGE",
    "Enchantment Cultivating 9": "ENCHANTMENT_CULTIVATING_9",
    "Enchantment Expertise 7": "ENCHANTMENT_EXPERTISE_7",
    "Enchantment Expertise 6": "ENCHANTMENT_EXPERTISE_6",
    "Enchantment Expertise 9": "ENCHANTMENT_EXPERTISE_9",
    "Enchantment Cultivating 7": "ENCHANTMENT_CULTIVATING_7",
    "Enchantment Expertise 8": "ENCHANTMENT_EXPERTISE_8",
    "Enchantment Cultivating 8": "ENCHANTMENT_CULTIVATING_8",
    "Enchantment Cultivating 5": "ENCHANTMENT_CULTIVATING_5",
    "Ender Stone": "ENDER_STONE",
    "Essence Crimson": "ESSENCE_CRIMSON",
    "Enchantment Cultivating 6": "ENCHANTMENT_CULTIVATING_6",
    "Enchantment Cultivating 3": "ENCHANTMENT_CULTIVATING_3",
    "Enchantment Cultivating 4": "ENCHANTMENT_CULTIVATING_4",
    "Enchantment Cultivating 1": "ENCHANTMENT_CULTIVATING_1",
    "Enchantment Vampirism 1": "ENCHANTMENT_VAMPIRISM_1",
    "Enchantment Vampirism 2": "ENCHANTMENT_VAMPIRISM_2",
    "Enchantment Cultivating 2": "ENCHANTMENT_CULTIVATING_2",
    Quartz: "QUARTZ",
    "Jerry Box Purple": "JERRY_BOX_PURPLE",
    "Enchantment Ultimate Soul Eater 1": "ENCHANTMENT_ULTIMATE_SOUL_EATER_1",
    "Salmon Opal": "SALMON_OPAL",
    Chum: "CHUM",
    "Enchantment Ultimate Soul Eater 3": "ENCHANTMENT_ULTIMATE_SOUL_EATER_3",
    "Enchantment Ultimate Soul Eater 2": "ENCHANTMENT_ULTIMATE_SOUL_EATER_2",
    "Enchantment Ultimate Soul Eater 5": "ENCHANTMENT_ULTIMATE_SOUL_EATER_5",
    "Enchantment Ultimate Soul Eater 4": "ENCHANTMENT_ULTIMATE_SOUL_EATER_4",
    "Magma Cream": "MAGMA_CREAM",
    "Enchanted Compost": "ENCHANTED_COMPOST",
    "Enchantment Chance 2": "ENCHANTMENT_CHANCE_2",
    "Enchanted Mithril": "ENCHANTED_MITHRIL",
    "Red Gift": "RED_GIFT",
    "Enchantment Chance 1": "ENCHANTMENT_CHANCE_1",
    "Fel Pearl": "FEL_PEARL",
    "Enchantment Chance 5": "ENCHANTMENT_CHANCE_5",
    "Enchantment Chance 4": "ENCHANTMENT_CHANCE_4",
    "Enchanted Feather": "ENCHANTED_FEATHER",
    "Enchanted Oak Log": "ENCHANTED_OAK_LOG",
    "Enchantment Chance 3": "ENCHANTMENT_CHANCE_3",
    "Enchantment Green Thumb 5": "ENCHANTMENT_GREEN_THUMB_5",
    "Enchantment Knockback 2": "ENCHANTMENT_KNOCKBACK_2",
    "White Gift": "WHITE_GIFT",
    "Enchantment Knockback 1": "ENCHANTMENT_KNOCKBACK_1",
    "Enchantment Green Thumb 1": "ENCHANTMENT_GREEN_THUMB_1",
    "Enchantment Ultimate Flash 2": "ENCHANTMENT_ULTIMATE_FLASH_2",
    "Enchantment Green Thumb 2": "ENCHANTMENT_GREEN_THUMB_2",
    "Enchantment Ultimate Flash 1": "ENCHANTMENT_ULTIMATE_FLASH_1",
    "Nether Stalk": "NETHER_STALK",
    "Enchantment Ultimate Flash 4": "ENCHANTMENT_ULTIMATE_FLASH_4",
    "Enchantment Green Thumb 3": "ENCHANTMENT_GREEN_THUMB_3",
    "Enchantment Green Thumb 4": "ENCHANTMENT_GREEN_THUMB_4",
    "Enchantment Ultimate Flash 3": "ENCHANTMENT_ULTIMATE_FLASH_3",
    "Enchantment First Strike 1": "ENCHANTMENT_FIRST_STRIKE_1",
    "Horseman Candle": "HORSEMAN_CANDLE",
    "Red Rose": "RED_ROSE",
    "Enchantment First Strike 5": "ENCHANTMENT_FIRST_STRIKE_5",
    "Enchantment Ultimate Flash 5": "ENCHANTMENT_ULTIMATE_FLASH_5",
    "Enchantment First Strike 4": "ENCHANTMENT_FIRST_STRIKE_4",
    "Enchantment First Strike 3": "ENCHANTMENT_FIRST_STRIKE_3",
    "Enchantment First Strike 2": "ENCHANTMENT_FIRST_STRIKE_2",
    "Golden Ball": "GOLDEN_BALL",
    "Enchantment Turbo Pumpkin 1": "ENCHANTMENT_TURBO_PUMPKIN_1",
    "Enchantment Turbo Pumpkin 2": "ENCHANTMENT_TURBO_PUMPKIN_2",
    "Enchantment Turbo Pumpkin 3": "ENCHANTMENT_TURBO_PUMPKIN_3",
    "Enchantment Turbo Pumpkin 4": "ENCHANTMENT_TURBO_PUMPKIN_4",
    "Enchantment Turbo Pumpkin 5": "ENCHANTMENT_TURBO_PUMPKIN_5",
    "Empty Chum Bucket": "EMPTY_CHUM_BUCKET",
    "Giant Fragment Boulder": "GIANT_FRAGMENT_BOULDER",
    Leather: "LEATHER",
    "Magma Fish": "MAGMA_FISH",
    "Soul String": "SOUL_STRING",
    "Enchantment Expertise 3": "ENCHANTMENT_EXPERTISE_3",
    "Enchantment Expertise 2": "ENCHANTMENT_EXPERTISE_2",
    "Enchantment Expertise 5": "ENCHANTMENT_EXPERTISE_5",
    "Enchantment Expertise 4": "ENCHANTMENT_EXPERTISE_4",
    "Enchanted Bread": "ENCHANTED_BREAD",
    "Fuming Potato Book": "FUMING_POTATO_BOOK",
    "Enchantment Expertise 1": "ENCHANTMENT_EXPERTISE_1",
    "Enchantment Ultimate Fatal Tempo 5": "ENCHANTMENT_ULTIMATE_FATAL_TEMPO_5",
    "Enchantment Ultimate Fatal Tempo 3": "ENCHANTMENT_ULTIMATE_FATAL_TEMPO_3",
    "Enchantment Depth Strider 2": "ENCHANTMENT_DEPTH_STRIDER_2",
    "Enchantment Blessing 2": "ENCHANTMENT_BLESSING_2",
    "Sulphur Ore": "SULPHUR_ORE",
    "Flawed Sapphire Gem": "FLAWED_SAPPHIRE_GEM",
    "Enchantment Ultimate Fatal Tempo 4": "ENCHANTMENT_ULTIMATE_FATAL_TEMPO_4",
    "Enchantment Depth Strider 3": "ENCHANTMENT_DEPTH_STRIDER_3",
    "Enchantment Blessing 3": "ENCHANTMENT_BLESSING_3",
    "Enchantment Ultimate Fatal Tempo 1": "ENCHANTMENT_ULTIMATE_FATAL_TEMPO_1",
    "Enchantment Ultimate Fatal Tempo 2": "ENCHANTMENT_ULTIMATE_FATAL_TEMPO_2",
    "Enchantment Blessing 1": "ENCHANTMENT_BLESSING_1",
    "Enchantment Blessing 6": "ENCHANTMENT_BLESSING_6",
    "Perfect Sapphire Gem": "PERFECT_SAPPHIRE_GEM",
    "Enchantment Blessing 4": "ENCHANTMENT_BLESSING_4",
    "Snow Block": "SNOW_BLOCK",
    "Enchantment Blessing 5": "ENCHANTMENT_BLESSING_5",
    "Enchanted Baked Potato": "ENCHANTED_BAKED_POTATO",
    "Agarimoo Tongue": "AGARIMOO_TONGUE",
    Compactor: "COMPACTOR",
    "Frozen Bauble": "FROZEN_BAUBLE",
    Mandraa: "MANDRAA",
    "Enchantment Depth Strider 1": "ENCHANTMENT_DEPTH_STRIDER_1",
    "Spooky Shard": "SPOOKY_SHARD",
    "Enchantment Champion 1": "ENCHANTMENT_CHAMPION_1",
    "Enchantment Champion 3": "ENCHANTMENT_CHAMPION_3",
    "Enchantment Champion 2": "ENCHANTMENT_CHAMPION_2",
    "Enchantment Champion 5": "ENCHANTMENT_CHAMPION_5",
    "Enchanted Potato": "ENCHANTED_POTATO",
    "Enchanted Lush Berberis": "ENCHANTED_LUSH_BERBERIS",
    "Enchantment Champion 4": "ENCHANTMENT_CHAMPION_4",
    "Radioactive Vial": "RADIOACTIVE_VIAL",
    "Enchantment Champion 7": "ENCHANTMENT_CHAMPION_7",
    "Enchanted Slime Ball": "ENCHANTED_SLIME_BALL",
    "Enchantment Champion 6": "ENCHANTMENT_CHAMPION_6",
    "Enchantment Champion 9": "ENCHANTMENT_CHAMPION_9",
    "Enchantment Champion 8": "ENCHANTMENT_CHAMPION_8",
    "Bulky Stone": "BULKY_STONE",
    "Enchantment Snipe 3": "ENCHANTMENT_SNIPE_3",
    "Enchanted Red Mushroom": "ENCHANTED_RED_MUSHROOM",
    "Enchantment Snipe 2": "ENCHANTMENT_SNIPE_2",
    "Enchantment Snipe 1": "ENCHANTMENT_SNIPE_1",
    "Enchantment Respiration 3": "ENCHANTMENT_RESPIRATION_3",
    "Enchantment Ultimate One For All 0": "ENCHANTMENT_ULTIMATE_ONE_FOR_ALL_0",
    "Enchantment Ultimate One For All 1": "ENCHANTMENT_ULTIMATE_ONE_FOR_ALL_1",
    "Enchantment Snipe 4": "ENCHANTMENT_SNIPE_4",
    "Great White Tooth Meal": "GREAT_WHITE_TOOTH_MEAL",
    "Enchantment Respiration 1": "ENCHANTMENT_RESPIRATION_1",
    "Enchantment Respiration 2": "ENCHANTMENT_RESPIRATION_2",
    "Full Jaw Fanging Kit": "FULL_JAW_FANGING_KIT",
    "Enchanted Cake": "ENCHANTED_CAKE",
    Pumpkin: "PUMPKIN",
    Wheat: "WHEAT",
    "Nurse Shark Tooth": "NURSE_SHARK_TOOTH",
    "Enchantment Reflection 5": "ENCHANTMENT_REFLECTION_5",
    "Enchantment Reflection 4": "ENCHANTMENT_REFLECTION_4",
    "Enchantment Ultimate Bank 5": "ENCHANTMENT_ULTIMATE_BANK_5",
    "Enchantment Ultimate Legion 1": "ENCHANTMENT_ULTIMATE_LEGION_1",
    "Enchantment Ultimate Bank 2": "ENCHANTMENT_ULTIMATE_BANK_2",
    "Enchantment Ultimate Bank 1": "ENCHANTMENT_ULTIMATE_BANK_1",
    "Enchantment Ultimate Legion 2": "ENCHANTMENT_ULTIMATE_LEGION_2",
    "Enchanted Spider Eye": "ENCHANTED_SPIDER_EYE",
    "Enchantment Ultimate Bank 4": "ENCHANTMENT_ULTIMATE_BANK_4",
    "Enchantment Ultimate Bank 3": "ENCHANTMENT_ULTIMATE_BANK_3",
    "Enchantment Ultimate Legion 5": "ENCHANTMENT_ULTIMATE_LEGION_5",
    "Enchantment Reflection 1": "ENCHANTMENT_REFLECTION_1",
    "Enchantment Ultimate Legion 3": "ENCHANTMENT_ULTIMATE_LEGION_3",
    "Enchantment Reflection 3": "ENCHANTMENT_REFLECTION_3",
    "Enchantment Ultimate Legion 4": "ENCHANTMENT_ULTIMATE_LEGION_4",
    "Enchantment Reflection 2": "ENCHANTMENT_REFLECTION_2",
    "Raw Soulflow": "RAW_SOULFLOW",
    "Enchantment Triple Strike 1": "ENCHANTMENT_TRIPLE_STRIKE_1",
    "Enchantment Triple Strike 3": "ENCHANTMENT_TRIPLE_STRIKE_3",
    "Enchantment Triple Strike 2": "ENCHANTMENT_TRIPLE_STRIKE_2",
    "Enchantment Prosperity 1": "ENCHANTMENT_PROSPERITY_1",
    "Raw Fish": "RAW_FISH",
    "Enchantment Prosperity 3": "ENCHANTMENT_PROSPERITY_3",
    "Enchantment Prosperity 2": "ENCHANTMENT_PROSPERITY_2",
    Yoggie: "YOGGIE",
    "Ice Hunk": "ICE_HUNK",
    "Perfect Jasper Gem": "PERFECT_JASPER_GEM",
    "Enchantment Prosperity 5": "ENCHANTMENT_PROSPERITY_5",
    "Enchantment Hecatomb 10": "ENCHANTMENT_HECATOMB_10",
    "Enchantment Prosperity 4": "ENCHANTMENT_PROSPERITY_4",
    "Control Switch": "CONTROL_SWITCH",
    "Enchantment Counter Strike 3": "ENCHANTMENT_COUNTER_STRIKE_3",
    "Diamond Spreading": "DIAMOND_SPREADING",
    "Enchantment Counter Strike 4": "ENCHANTMENT_COUNTER_STRIKE_4",
    "Enchantment Counter Strike 5": "ENCHANTMENT_COUNTER_STRIKE_5",
    "Tightly Tied Hay Bale": "TIGHTLY_TIED_HAY_BALE",
    "Nether Stalk Distillate": "NETHER_STALK_DISTILLATE",
    "Diver Fragment": "DIVER_FRAGMENT",
    "Enchantment Wither Hunter 0": "ENCHANTMENT_WITHER_HUNTER_0",
    "Enchantment Spiked Hook 5": "ENCHANTMENT_SPIKED_HOOK_5",
    "Enchantment Spiked Hook 6": "ENCHANTMENT_SPIKED_HOOK_6",
    "Enchantment Spiked Hook 3": "ENCHANTMENT_SPIKED_HOOK_3",
    "Enchantment Spiked Hook 4": "ENCHANTMENT_SPIKED_HOOK_4",
    "Essence Diamond": "ESSENCE_DIAMOND",
    "Enchantment Lethality 1": "ENCHANTMENT_LETHALITY_1",
    "Enchantment Lethality 2": "ENCHANTMENT_LETHALITY_2",
    "Enchantment Lethality 3": "ENCHANTMENT_LETHALITY_3",
    "Enchantment Lethality 4": "ENCHANTMENT_LETHALITY_4",
    "Enchantment Lethality 5": "ENCHANTMENT_LETHALITY_5",
    "Enchantment Lethality 6": "ENCHANTMENT_LETHALITY_6",
    "Enchantment Cleave 2": "ENCHANTMENT_CLEAVE_2",
    "Enchantment Cleave 1": "ENCHANTMENT_CLEAVE_1",
    "Enchantment Rejuvenate 1": "ENCHANTMENT_REJUVENATE_1",
    "Huge Mushroom 1": "HUGE_MUSHROOM_1",
    "Enchantment Cleave 4": "ENCHANTMENT_CLEAVE_4",
    "Huge Mushroom 2": "HUGE_MUSHROOM_2",
    "Enchantment Cleave 3": "ENCHANTMENT_CLEAVE_3",
    "Enchantment Cleave 6": "ENCHANTMENT_CLEAVE_6",
    "Enchantment Cleave 5": "ENCHANTMENT_CLEAVE_5",
    "Enchantment Rejuvenate 5": "ENCHANTMENT_REJUVENATE_5",
    "Enchantment Vicious 3": "ENCHANTMENT_VICIOUS_3",
    "Enchantment Vicious 4": "ENCHANTMENT_VICIOUS_4",
    "Enchantment Rejuvenate 4": "ENCHANTMENT_REJUVENATE_4",
    "Enchantment Rejuvenate 3": "ENCHANTMENT_REJUVENATE_3",
    "Enchantment Vicious 5": "ENCHANTMENT_VICIOUS_5",
    "Enchantment Rejuvenate 2": "ENCHANTMENT_REJUVENATE_2",
    String: "STRING",
    "Crude Gabagool": "CRUDE_GABAGOOL",
    "Dragon Scale": "DRAGON_SCALE",
    "Enchantment Spiked Hook 1": "ENCHANTMENT_SPIKED_HOOK_1",
    "Enchantment Spiked Hook 2": "ENCHANTMENT_SPIKED_HOOK_2",
    "Enchanted Cactus Green": "ENCHANTED_CACTUS_GREEN",
    "Booster Cookie": "BOOSTER_COOKIE",
    "Enchanted Cookie": "ENCHANTED_COOKIE",
    "Amalgamated Crimsonite New": "AMALGAMATED_CRIMSONITE_NEW",
    "Strong Fragment": "STRONG_FRAGMENT",
    Mycel: "MYCEL",
    "Auto Smelter": "AUTO_SMELTER",
    Wool: "WOOL",
    "Enchantment Turbo Carrot 2": "ENCHANTMENT_TURBO_CARROT_2",
    "Enchantment Turbo Carrot 1": "ENCHANTMENT_TURBO_CARROT_1",
    "Enchantment Giant Killer 4": "ENCHANTMENT_GIANT_KILLER_4",
    "Whipped Magma Cream": "WHIPPED_MAGMA_CREAM",
    "Enchantment Giant Killer 5": "ENCHANTMENT_GIANT_KILLER_5",
    "Enchantment Giant Killer 2": "ENCHANTMENT_GIANT_KILLER_2",
    "Dragon Horn": "DRAGON_HORN",
    "Perfect Amber Gem": "PERFECT_AMBER_GEM",
    "Enchantment Giant Killer 3": "ENCHANTMENT_GIANT_KILLER_3",
    "Enchantment Giant Killer 6": "ENCHANTMENT_GIANT_KILLER_6",
    Flint: "FLINT",
    "Enchantment Giant Killer 7": "ENCHANTMENT_GIANT_KILLER_7",
    "Enchantment Triple Strike 5": "ENCHANTMENT_TRIPLE_STRIKE_5",
    "Enchanted Spruce Log": "ENCHANTED_SPRUCE_LOG",
    "Hardened Wood": "HARDENED_WOOD",
    "Enchantment Triple Strike 4": "ENCHANTMENT_TRIPLE_STRIKE_4",
    "Enchantment Ultimate Inferno 1": "ENCHANTMENT_ULTIMATE_INFERNO_1",
    "Enchantment Ultimate Inferno 3": "ENCHANTMENT_ULTIMATE_INFERNO_3",
    "Enchanted Quartz Block": "ENCHANTED_QUARTZ_BLOCK",
    "Enchantment Ultimate Inferno 2": "ENCHANTMENT_ULTIMATE_INFERNO_2",
    "Heavy Gabagool": "HEAVY_GABAGOOL",
    "Enchantment Ultimate Inferno 5": "ENCHANTMENT_ULTIMATE_INFERNO_5",
    "Enchantment Ultimate Inferno 4": "ENCHANTMENT_ULTIMATE_INFERNO_4",
    "Green Candy": "GREEN_CANDY",
    "Eccentric Painting": "ECCENTRIC_PAINTING",
    "Reaper Pepper": "REAPER_PEPPER",
    "Enchantment Aqua Affinity 1": "ENCHANTMENT_AQUA_AFFINITY_1",
    Gravel: "GRAVEL",
    "Enchanted Packed Ice": "ENCHANTED_PACKED_ICE",
    "Enchanted Prismarine Shard": "ENCHANTED_PRISMARINE_SHARD",
    "Spirit Decoy": "SPIRIT_DECOY",
    "Enchantment Turbo Carrot 4": "ENCHANTMENT_TURBO_CARROT_4",
    "Hypergolic Gabagool": "HYPERGOLIC_GABAGOOL",
    "Enchantment Turbo Carrot 3": "ENCHANTMENT_TURBO_CARROT_3",
    "Enchanted Carrot Stick": "ENCHANTED_CARROT_STICK",
    "Enchantment Turbo Carrot 5": "ENCHANTMENT_TURBO_CARROT_5",
    "Enchantment Turbo Cane 4": "ENCHANTMENT_TURBO_CANE_4",
    "Drill Engine": "DRILL_ENGINE",
    "Enchantment Turbo Cane 3": "ENCHANTMENT_TURBO_CANE_3",
    "Enchantment Turbo Cane 2": "ENCHANTMENT_TURBO_CANE_2",
    "Enchantment Turbo Cane 1": "ENCHANTMENT_TURBO_CANE_1",
    "Enchantment Turbo Cane 5": "ENCHANTMENT_TURBO_CANE_5",
    "Box Of Seeds": "BOX_OF_SEEDS",
    "Xlarge Enchanted Chest": "XLARGE_ENCHANTED_CHEST",
    "Third Master Star": "THIRD_MASTER_STAR",
    "Vitamin Death": "VITAMIN_DEATH",
    "Pet Item Tier Boost Drop": "PET_ITEM_TIER_BOOST_DROP",
    Netherrack: "NETHERRACK",
    Compost: "COMPOST",
    Fermento: "FERMENTO",
    "Candy Corn": "CANDY_CORN",
    "Midas Jewel": "MIDAS_JEWEL",
    "Premium Flesh": "PREMIUM_FLESH",
    Squash: "SQUASH",
    "Rough Amethyst Gem": "ROUGH_AMETHYST_GEM",
    "Flawless Ruby Gem": "FLAWLESS_RUBY_GEM",
    "Null Atom": "NULL_ATOM",
    "Blessed Bait": "BLESSED_BAIT",
    "Pure Mithril": "PURE_MITHRIL",
    "Rock Candy": "ROCK_CANDY",
    "Enchantment Fortune 1": "ENCHANTMENT_FORTUNE_1",
    "Enchantment Fortune 2": "ENCHANTMENT_FORTUNE_2",
    "Oak Wood": "LOG",
    "Enchantment Fortune 3": "ENCHANTMENT_FORTUNE_3",
    "Enchantment Fortune 4": "ENCHANTMENT_FORTUNE_4",
    "Searing Stone": "SEARING_STONE",
    "Enchantment Flame 2": "ENCHANTMENT_FLAME_2",
    "Enchantment Flame 1": "ENCHANTMENT_FLAME_1",
    "Rough Jade Gem": "ROUGH_JADE_GEM",
    "Enchanted Jungle Log": "ENCHANTED_JUNGLE_LOG",
    "Wood Singularity": "WOOD_SINGULARITY",
    "Iron Ingot": "IRON_INGOT",
    "Gemstone Mixture": "GEMSTONE_MIXTURE",
    "Enchantment Divine Gift 3": "ENCHANTMENT_DIVINE_GIFT_3",
    "Enchantment Divine Gift 2": "ENCHANTMENT_DIVINE_GIFT_2",
    "Enchantment Divine Gift 1": "ENCHANTMENT_DIVINE_GIFT_1",
    "Spirit Bone": "SPIRIT_BONE",
    "Rough Sapphire Gem": "ROUGH_SAPPHIRE_GEM",
    "Mite Gel": "MITE_GEL",
    "Revenant Viscera": "REVENANT_VISCERA",
    "Enchantment Giant Killer 1": "ENCHANTMENT_GIANT_KILLER_1",
    "Tarantula Silk": "TARANTULA_SILK",
    "Titanic Exp Bottle": "TITANIC_EXP_BOTTLE",
    "Enchantment Frail 2": "ENCHANTMENT_FRAIL_2",
    "Enchantment Frail 1": "ENCHANTMENT_FRAIL_1",
    "Enchantment Frail 4": "ENCHANTMENT_FRAIL_4",
    "Super Compactor 3000": "SUPER_COMPACTOR_3000",
    "Super Egg": "SUPER_EGG",
    "Enchantment Frail 3": "ENCHANTMENT_FRAIL_3",
    "Enchantment Frail 6": "ENCHANTMENT_FRAIL_6",
    "Enchantment Frail 5": "ENCHANTMENT_FRAIL_5",
    "Mithril Ore": "MITHRIL_ORE",
    "Enchanted Paper": "ENCHANTED_PAPER",
    "Hot Stuff": "HOT_STUFF",
    "Suspicious Vial": "SUSPICIOUS_VIAL",
    "Dirt Bottle": "DIRT_BOTTLE",
    "Rough Topaz Gem": "ROUGH_TOPAZ_GEM",
    "Enchanted Obsidian": "ENCHANTED_OBSIDIAN",
    "Rough Opal Gem": "ROUGH_OPAL_GEM",
    "Enchantment Efficiency 10": "ENCHANTMENT_EFFICIENCY_10",
    "Werewolf Skin": "WEREWOLF_SKIN",
    "Enchantment Syphon 3": "ENCHANTMENT_SYPHON_3",
    "Enchantment Syphon 2": "ENCHANTMENT_SYPHON_2",
    "Enchantment Syphon 5": "ENCHANTMENT_SYPHON_5",
    "Enchantment Syphon 4": "ENCHANTMENT_SYPHON_4",
    "Enchanted Red Sand Cube": "ENCHANTED_RED_SAND_CUBE",
    "Enchanted Raw Fish": "ENCHANTED_RAW_FISH",
    "Enchantment Execute 6": "ENCHANTMENT_EXECUTE_6",
    "Berberis Fuel Injector": "BERBERIS_FUEL_INJECTOR",
    "Enchantment Infinite Quiver 10": "ENCHANTMENT_INFINITE_QUIVER_10",
    "Enchantment Execute 3": "ENCHANTMENT_EXECUTE_3",
    "Enchantment Execute 2": "ENCHANTMENT_EXECUTE_2",
    "Enchantment Execute 5": "ENCHANTMENT_EXECUTE_5",
    "Enchantment Syphon 1": "ENCHANTMENT_SYPHON_1",
    "Enchantment Execute 4": "ENCHANTMENT_EXECUTE_4",
    "Enchantment Smite 7": "ENCHANTMENT_SMITE_7",
    "Enchantment Looting 4": "ENCHANTMENT_LOOTING_4",
    "Enchantment Scavenger 3": "ENCHANTMENT_SCAVENGER_3",
    "Enchantment Scavenger 4": "ENCHANTMENT_SCAVENGER_4",
    "Enchantment Looting 3": "ENCHANTMENT_LOOTING_3",
    "Enchantment Scavenger 1": "ENCHANTMENT_SCAVENGER_1",
    "Enchantment Looting 2": "ENCHANTMENT_LOOTING_2",
    "Enchantment Execute 1": "ENCHANTMENT_EXECUTE_1",
    "Fuel Gabagool": "FUEL_GABAGOOL",
    "Enchantment Scavenger 2": "ENCHANTMENT_SCAVENGER_2",
    "Enchantment Looting 1": "ENCHANTMENT_LOOTING_1",
    "Enchantment Cubism 2": "ENCHANTMENT_CUBISM_2",
    "Enchantment Cubism 3": "ENCHANTMENT_CUBISM_3",
    "Enchantment Scavenger 5": "ENCHANTMENT_SCAVENGER_5",
    "Enchantment Cubism 1": "ENCHANTMENT_CUBISM_1",
    "Shark Bait": "SHARK_BAIT",
    "Jungle Key": "JUNGLE_KEY",
    "Jerry Box Blue": "JERRY_BOX_BLUE",
    "Enchantment Looting 5": "ENCHANTMENT_LOOTING_5",
    "Enchanted Slime Block": "ENCHANTED_SLIME_BLOCK",
    "Enchantment Cubism 6": "ENCHANTMENT_CUBISM_6",
    "Scorched Books": "SCORCHED_BOOKS",
    Sulphur: "SULPHUR",
    "Fine Sapphire Gem": "FINE_SAPPHIRE_GEM",
    "Enchantment Cubism 4": "ENCHANTMENT_CUBISM_4",
    "Enchantment Smite 1": "ENCHANTMENT_SMITE_1",
    "Enchantment Cubism 5": "ENCHANTMENT_CUBISM_5",
    "Enchantment Smite 2": "ENCHANTMENT_SMITE_2",
    "Golden Powder": "GOLDEN_POWDER",
    "Enchantment Expertise 10": "ENCHANTMENT_EXPERTISE_10",
    "Enchantment Smite 3": "ENCHANTMENT_SMITE_3",
    "Enchantment Smite 4": "ENCHANTMENT_SMITE_4",
    "Enchanted Carrot": "ENCHANTED_CARROT",
    "Enchantment Smite 5": "ENCHANTMENT_SMITE_5",
    "Enchantment Smite 6": "ENCHANTMENT_SMITE_6",
    "Rotten Flesh": "ROTTEN_FLESH",
    "Enchantment Hecatomb 2": "ENCHANTMENT_HECATOMB_2",
    "Enchantment Hecatomb 3": "ENCHANTMENT_HECATOMB_3",
    "Enchantment Hecatomb 1": "ENCHANTMENT_HECATOMB_1",
    "Enchantment Hecatomb 6": "ENCHANTMENT_HECATOMB_6",
    "Enchantment Hecatomb 7": "ENCHANTMENT_HECATOMB_7",
    "Enchantment Hecatomb 4": "ENCHANTMENT_HECATOMB_4",
    "Dungeon Chest Key": "DUNGEON_CHEST_KEY",
    "Enchantment Hecatomb 5": "ENCHANTMENT_HECATOMB_5",
    "Enchantment Hecatomb 8": "ENCHANTMENT_HECATOMB_8",
    "Enchantment Hecatomb 9": "ENCHANTMENT_HECATOMB_9",
    "Inflatable Jerry": "INFLATABLE_JERRY",
    "Flawed Topaz Gem": "FLAWED_TOPAZ_GEM",
    "Enchantment Sunder 1": "ENCHANTMENT_SUNDER_1",
    "Lapis Crystal": "LAPIS_CRYSTAL",
    "Fine Amethyst Gem": "FINE_AMETHYST_GEM",
    "Enchantment Transylvanian 5": "ENCHANTMENT_TRANSYLVANIAN_5",
    "Red Sand": "SAND:1",
    "Enchanted Rabbit": "ENCHANTED_RABBIT",
    "Medium Enchanted Chest": "MEDIUM_ENCHANTED_CHEST",
    "Toxic Arrow Poison": "TOXIC_ARROW_POISON",
    "Enchantment Transylvanian 4": "ENCHANTMENT_TRANSYLVANIAN_4",
    "Enchantment Sunder 4": "ENCHANTMENT_SUNDER_4",
    "Enchantment Sunder 5": "ENCHANTMENT_SUNDER_5",
    "Enchantment Sunder 2": "ENCHANTMENT_SUNDER_2",
    "Enchantment Sunder 3": "ENCHANTMENT_SUNDER_3",
    "Mutant Nether Stalk": "MUTANT_NETHER_STALK",
    "Enchantment Luck 6": "ENCHANTMENT_LUCK_6",
    "Enchantment Luck 7": "ENCHANTMENT_LUCK_7",
    "Enchantment Luck 2": "ENCHANTMENT_LUCK_2",
    "Flawless Amber Gem": "FLAWLESS_AMBER_GEM",
    "Enchantment Luck 3": "ENCHANTMENT_LUCK_3",
    "Enchanted Blaze Powder": "ENCHANTED_BLAZE_POWDER",
    "Enchantment Luck 4": "ENCHANTMENT_LUCK_4",
    "Enchantment Luck 5": "ENCHANTMENT_LUCK_5",
    "Enchanted Sulphur Cube": "ENCHANTED_SULPHUR_CUBE",
    "Summoning Eye": "SUMMONING_EYE",
    "Enchantment Infinite Quiver 8": "ENCHANTMENT_INFINITE_QUIVER_8",
    "Enchantment Infinite Quiver 9": "ENCHANTMENT_INFINITE_QUIVER_9",
    "Enchantment Infinite Quiver 6": "ENCHANTMENT_INFINITE_QUIVER_6",
    "Fish Bait": "FISH_BAIT",
    "Enchantment Infinite Quiver 7": "ENCHANTMENT_INFINITE_QUIVER_7",
    "Enchantment Luck 1": "ENCHANTMENT_LUCK_1",
    "Enchantment Turbo Potato 3": "ENCHANTMENT_TURBO_POTATO_3",
    "Enchantment Ultimate Wisdom 4": "ENCHANTMENT_ULTIMATE_WISDOM_4",
    "Enchantment Infinite Quiver 4": "ENCHANTMENT_INFINITE_QUIVER_4",
    "Enchantment Bane Of Arthropods 2": "ENCHANTMENT_BANE_OF_ARTHROPODS_2",
    "Enchantment Ultimate Wisdom 5": "ENCHANTMENT_ULTIMATE_WISDOM_5",
    "Enchantment Turbo Potato 4": "ENCHANTMENT_TURBO_POTATO_4",
    "Enchantment Infinite Quiver 5": "ENCHANTMENT_INFINITE_QUIVER_5",
    "Enchantment Bane Of Arthropods 3": "ENCHANTMENT_BANE_OF_ARTHROPODS_3",
    "Enchantment Turbo Potato 5": "ENCHANTMENT_TURBO_POTATO_5",
    "Enchantment Infinite Quiver 2": "ENCHANTMENT_INFINITE_QUIVER_2",
    "Enchantment Infinite Quiver 3": "ENCHANTMENT_INFINITE_QUIVER_3",
    "Enchantment Bane Of Arthropods 1": "ENCHANTMENT_BANE_OF_ARTHROPODS_1",
    "Enchantment Bane Of Arthropods 6": "ENCHANTMENT_BANE_OF_ARTHROPODS_6",
    "Enchantment Ultimate Wisdom 1": "ENCHANTMENT_ULTIMATE_WISDOM_1",
    "Enchantment Bane Of Arthropods 7": "ENCHANTMENT_BANE_OF_ARTHROPODS_7",
    "Winter Water Orb": "WINTER_WATER_ORB",
    "Enchantment Infinite Quiver 1": "ENCHANTMENT_INFINITE_QUIVER_1",
    "Enchantment Turbo Potato 1": "ENCHANTMENT_TURBO_POTATO_1",
    "Enchantment Ultimate Wisdom 2": "ENCHANTMENT_ULTIMATE_WISDOM_2",
    "Enchantment Bane Of Arthropods 4": "ENCHANTMENT_BANE_OF_ARTHROPODS_4",
    "Enchantment Turbo Potato 2": "ENCHANTMENT_TURBO_POTATO_2",
    "Enchantment Ultimate Wisdom 3": "ENCHANTMENT_ULTIMATE_WISDOM_3",
    "Enchantment Bane Of Arthropods 5": "ENCHANTMENT_BANE_OF_ARTHROPODS_5",
};

const express = require("express");
const router = express.Router();

router.get("/", async (req, res) => {
    const items = Object.keys(itemDict);
    console.log(req.query);
    const searchQuery = req.query.product.toLowerCase();
    const searchResults = items.filter((item) =>
        item.toLowerCase().includes(searchQuery)
    );

    const filteredDict = {};
    searchResults.forEach((item) => {
        filteredDict[item] = itemDict[item];
    });
    console.log(Object.keys(itemDict));
    // console.log(filteredDict)
    // console.log(searchResults)
    res.send(filteredDict);
});

module.exports = router;
